In [2]:
fn='../data/AAPL.csv'

In [3]:
with open(fn, 'r') as f:
    for _ in range(5):
        print(f.readline(), end='')

Date,HIGH,CLOSE,LOW,OPEN,COUNT,VOLUME
2020-04-01,248.72,240.91,239.13,246.5,460606.0,44054638.0
2020-04-02,245.15,244.93,236.9,240.34,380294.0,41483493.0
2020-04-03,245.7,241.41,238.9741,242.8,293699.0,32470017.0
2020-04-06,263.11,262.47,249.38,250.9,486681.0,50455071.0

In [4]:
import csv

In [5]:
csv_reader=csv.reader(open(fn,'r'))

In [6]:
data=list(csv_reader)

In [7]:
data[:5]

[['Date', 'HIGH', 'CLOSE', 'LOW', 'OPEN', 'COUNT', 'VOLUME'],
 ['2020-04-01',
  '248.72',
  '240.91',
  '239.13',
  '246.5',
  '460606.0',
  '44054638.0'],
 ['2020-04-02',
  '245.15',
  '244.93',
  '236.9',
  '240.34',
  '380294.0',
  '41483493.0'],
 ['2020-04-03',
  '245.7',
  '241.41',
  '238.9741',
  '242.8',
  '293699.0',
  '32470017.0'],
 ['2020-04-06',
  '263.11',
  '262.47',
  '249.38',
  '250.9',
  '486681.0',
  '50455071.0']]

In [8]:
csv_reader=csv.DictReader(open(fn, 'r'))

In [9]:
data=list(csv_reader);

In [10]:
data[:3]

[{'Date': '2020-04-01',
  'HIGH': '248.72',
  'CLOSE': '240.91',
  'LOW': '239.13',
  'OPEN': '246.5',
  'COUNT': '460606.0',
  'VOLUME': '44054638.0'},
 {'Date': '2020-04-02',
  'HIGH': '245.15',
  'CLOSE': '244.93',
  'LOW': '236.9',
  'OPEN': '240.34',
  'COUNT': '380294.0',
  'VOLUME': '41483493.0'},
 {'Date': '2020-04-03',
  'HIGH': '245.7',
  'CLOSE': '241.41',
  'LOW': '238.9741',
  'OPEN': '242.8',
  'COUNT': '293699.0',
  'VOLUME': '32470017.0'}]

In [11]:
sum([float(l['CLOSE']) for l in data]) / len(data)

247.43

In [12]:
import pandas as pd
data = pd.read_csv(fn, index_col=0, parse_dates=True)

In [13]:
data.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 4 entries, 2020-04-01 to 2020-04-06
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   HIGH    4 non-null      float64
 1   CLOSE   4 non-null      float64
 2   LOW     4 non-null      float64
 3   OPEN    4 non-null      float64
 4   COUNT   4 non-null      float64
 5   VOLUME  4 non-null      float64
dtypes: float64(6)
memory usage: 224.0 bytes

In [14]:
data.tail()

              HIGH   CLOSE       LOW    OPEN     COUNT      VOLUME
Date
2020-04-01  248.72  240.91  239.1300  246.50  460606.0  44054638.0
2020-04-02  245.15  244.93  236.9000  240.34  380294.0  41483493.0
2020-04-03  245.70  241.41  238.9741  242.80  293699.0  32470017.0
2020-04-06  263.11  262.47  249.3800  250.90  486681.0  50455071.0

In [15]:
data['CLOSE'].mean()

np.float64(247.43)

In [22]:
data.to_excel('./aapl.xlsx', sheet_name='AAPL')

In [23]:
data.to_json('./aapl.json')

In [24]:
data_copy1 = pd.read_excel('./aapl.xlsx', 'AAPL', index_col=0)

In [25]:
data_copy1.head()

              HIGH   CLOSE       LOW    OPEN   COUNT    VOLUME
Date
2020-04-01  248.72  240.91  239.1300  246.50  460606  44054638
2020-04-02  245.15  244.93  236.9000  240.34  380294  41483493
2020-04-03  245.70  241.41  238.9741  242.80  293699  32470017
2020-04-06  263.11  262.47  249.3800  250.90  486681  50455071

In [26]:
datacopy2 = pd.read_json('aapl.json')

In [27]:
datacopy2.head()

              HIGH   CLOSE       LOW    OPEN   COUNT    VOLUME
2020-04-01  248.72  240.91  239.1300  246.50  460606  44054638
2020-04-02  245.15  244.93  236.9000  240.34  380294  41483493
2020-04-03  245.70  241.41  238.9741  242.80  293699  32470017
2020-04-06  263.11  262.47  249.3800  250.90  486681  50455071