In [1]:
v = [1, 2, 3, 4, 5]

In [2]:
sm = [2 * i for i in v]

In [3]:
sm

[2, 4, 6, 8, 10]

In [5]:
2 * v

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [6]:
import numpy as np

In [7]:
a = np.array(v)

In [8]:
a

array([1, 2, 3, 4, 5])

In [9]:
type(a)

numpy.ndarray

In [10]:
2 * a

array([ 2,  4,  6,  8, 10])

In [12]:
a = np.arange(12).reshape((4, 3))

In [13]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
a**2

array([[  0,   1,   4],
       [  9,  16,  25],
       [ 36,  49,  64],
       [ 81, 100, 121]])

In [ ]:
a.mean()

np.float64(5.5)

In [17]:
a = np.arange(15).reshape(5, 3)

In [18]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [19]:
import pandas as pd

In [20]:
columns = list('abc')

In [21]:
columns

['a', 'b', 'c']

In [27]:
index = pd.date_range('2025-7-1', periods=5, freq='B')

In [28]:
index

DatetimeIndex(['2025-07-01', '2025-07-02', '2025-07-03', '2025-07-04',
               '2025-07-07'],
              dtype='datetime64[us]', freq='B')

In [ ]:
df = pd.DataFrame(a, columns=columns, index = index)

In [30]:
df

             a   b   c
2025-07-01   0   1   2
2025-07-02   3   4   5
2025-07-03   6   7   8
2025-07-04   9  10  11
2025-07-07  12  13  14

In [31]:
2 * df

             a   b   c
2025-07-01   0   2   4
2025-07-02   6   8  10
2025-07-03  12  14  16
2025-07-04  18  20  22
2025-07-07  24  26  28

In [32]:
df.sum()

a    30
b    35
c    40
dtype: int64

In [34]:
df.mean()

a    6.0
b    7.0
c    8.0
dtype: float64